version: '3'

services:
  node: 
    build:
      context: ./pratico-node
      dockerfile: Dockerfile
    image: lucasvidigal98/hello-express
    container_name: hello-express
    ports:
      - "3000:3000"
    networks:
      - minharede

networks:
  minharede:
    driver: bridge